import pandas as pd
import os
import sys
import re
from tqdm import tqdm

# Setup Path
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from utils.metrics import keyword_hit_rate, rouge_l_f1, bertscore_multilingual_batch
from utils.llm import hi_to_en_local, extract_answer_from_output

def is_hindi(text):
    """
    Detects if the text is Hindi based on Devanagari character presence.
    Ensures back-translation only happens for Hindi answers.
    """
    if not isinstance(text, str) or not text.strip():
        return False
    # Count characters in the Devanagari range (\u0900-\u097F)
    hindi_chars = len(re.findall(r'[\u0900-\u097F]', text))
    # If more than 10% of the string is Devanagari, treat as Hindi
    return (hindi_chars / len(text)) > 0.1

def main():
    # Load the results generated by 03_run_qa.py and 06_run_rag.py
    input_file = "outputs/runs/all_runs.csv"
    output_file = "outputs/evaluation/all_results.csv"
    
    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found.")
        return

    df = pd.read_csv(input_file)
    
    # Fill NaN and clean <think> tags (essential for Sarvam-30B)
    df['answer_hi'] = df['answer_hi'].fillna("").apply(extract_answer_from_output)

    # 1. Selective Back Translation Phase
    print("Starting Selective Back-Translation (Hindi -> English Only)...")
    back_translations = []
    
    for text in tqdm(df['answer_hi'], desc="Evaluating Language & Translating"):
        text_str = str(text).strip()
        
        if not text_str:
            back_translations.append("")
        elif is_hindi(text_str):
            # Direction: Hindi -> English (Apply translation)
            back_translations.append(hi_to_en_local(text_str))
        else:
            # Direction: English -> English (Skip translation to avoid noise)
            back_translations.append(text_str)
            
    df['back_en'] = back_translations

    # 2. Accuracy Metrics (Keyword Hits on English Back-translation)
    # Note: Using back_en ensures we compare English Keywords to English Text
    print("Calculating Keyword Hit Rates...")
    df['keyword_hit_rate'] = df.apply(
        lambda r: keyword_hit_rate(str(r['keywords_en']), str(r['back_en'])), 
        axis=1
    )

    # 3. Fluency Metrics (ROUGE-L on English Back-translation)
    print("Calculating ROUGE-L Scores...")
    df['rougeL_f1'] = df.apply(
        lambda r: rouge_l_f1(str(r['gold_answer_en']), str(r['back_en'])), 
        axis=1
    )

    # 4. Semantic Metrics (BERTScore on English Back-translation)
    print("Calculating BERTScore...")
    df['bertscore_f1'] = bertscore_multilingual_batch(
        df['gold_answer_en'].astype(str).tolist(), 
        df['back_en'].astype(str).tolist()
    )

    # Final Save
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    df.to_csv(output_file, index=False, encoding="utf-8-sig")
    print(f"Evaluation complete. Results saved to {output_file}")

if __name__ == "__main__":
    main()